version: "{build}"

clone_depth: 1

environment:
  matrix:
    - nodejs_version: 4.5.0

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
  - npm test

cache:
  - node_modules

matrix:
  fast_finish: true
